bridges = []
persistence_dir = '/tmp/tmp.DwKUkx70po/tryorama/M4FEbf'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'reactGraphql'
keystore_file = '[UNUSED]'
name = 'bob::reactGraphql::de1b6243-6f1f-40c3-9de0-ff50f4c80add'
public_address = 'HcSCIh8PcN6IG6zmpsYYmVch7M3Bhincwxrspg4xKooqsb5mJUD4HqA9fxrw6na'
test_agent = true

[[dnas]]
file = '/Users/philipbeadle/holochain/react-graphql-template/dna_src/dist/dna_src.dna.json'
hash = 'QmTD6ZSm8sLKBMmeAEdYMpha8popxYf7ZCULr77Nyv5Fgm'
id = 'note-test'
uuid = 'de1b6243-6f1f-40c3-9de0-ff50f4c80add'

[[instances]]
agent = 'reactGraphql'
dna = 'note-test'
id = 'reactGraphql'

[instances.storage]
path = '/tmp/tmp.DwKUkx70po/tryorama/M4FEbf/reactGraphql'
type = 'lmdb'

[[interfaces]]
admin = true
choose_free_port = false
id = 'tryorama-interface'

[[interfaces.instances]]
id = 'reactGraphql'

[interfaces.driver]
port = 33001
type = 'websocket'

[logger]
state_dump = false
type = 'debug'
[[logger.rules.rules]]
exclude = true
pattern = '^parity'

[[logger.rules.rules]]
exclude = true
pattern = '^mio'

[[logger.rules.rules]]
exclude = true
pattern = '^tokio'

[[logger.rules.rules]]
exclude = true
pattern = '^hyper'

[[logger.rules.rules]]
exclude = true
pattern = '^rusoto_core'

[[logger.rules.rules]]
exclude = true
pattern = '^want'

[[logger.rules.rules]]
exclude = true
pattern = '^rpc'

[[logger.rules.rules]]
exclude = false
pattern = '^holochain'

[[logger.rules.rules]]
exclude = false
pattern = '^lib3h'

[network]
sim2h_url = 'ws://localhost:9000'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = true
trace = false
